### PR TITLE
Add support for cerebro

### PR DESCRIPTION
**Pull request by jjungnickel**

### CODE REVIEW

**Comment by andrey-moor** [comment]
I'd keep it more or less synced up with https://github.com/pires/kubernetes-elasticsearch-cluster. Can you create similar PR there as well?

@clockworksoul your thoughts?

**Comment by jjungnickel** [comment]
@andrey-moor Yeah, I guess that makes sense

**Comment by clockworksoul** [comment]
I agree. I don't think the goal needs to be 1:1 exact, but we should keep in sync where we can.

**Comment by jalberto** [comment]
Cerebro does not follow Elastic release cycles, and is designed as a isolated client, so one cerebro can access every ES cluster.

i suggest to keep cerebro as a separated helm

**Comment by sagikazarmark** [comment]
Sounds reasonable

**Comment by jjungnickel** [comment]
I agree!

**Pull request closed without merging**
