### PR TITLE
Add travis build config for helm chart linting

### PR DESCRIPTION
**Pull request by sagikazarmark**

### CODE REVIEW

**Comment by clockworksoul** [comment]
LGTM! Thanks for taking this on.

Two tiny things: I fully acknowledge that these are the mother of all nitpicks, but can we standardize our `yaml` files to use the `.yaml` extension (unless Travis really wants `.yml`, of course) and some number of space indentations (the templates use 2; I don't care what the actual number is as long as it's consistent)?

**Comment by sagikazarmark** [comment]
I usually prefer 4 spaces for indentation, because 2 spaces are really unreadable. But helm charts seem to follow that practice. So I usually leave consistency when it comes to helm charts. :) Indenting with 4 spaces would be a huge work at this point, because of the go template parts which are not supported by IDEs. So I vote for inconsistency here, unless I convinced you.

As for the travis file: https://github.com/travis-ci/travis-ci/issues/672

**Comment by clockworksoul** [comment]
You're killin' me :)

I'm very reluctant to go to 4-space indenting in the templates... that be a mess to do with little real gain and would make them inconsistent with the apparent standard with the rest of the chart world.

But if you really like 4 spaces for the Travis file, oh, alright. 😄 

And as for the `.yaml` thing, oh well... /shrug

Merge away, my friend!

**Comment by sagikazarmark** [comment]
> I'm very reluctant to go to 4-space indenting in the templates... that be a mess to do with little real gain and would make them inconsistent with the apparent standard with the rest of the chart world.

Me too, but normally I hate 2 spacing.

Can you turn on travis to see if it works before merging?

**Comment by clockworksoul** [comment]
Travis enabled! 🙂

**Pull request merged**
